"""Error codes and the delivery error type shared by the planner and CLI."""

INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
SYMLINK_NOT_ALLOWED = "SYMLINK_NOT_ALLOWED"
PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
EMPTY_SELECTION = "EMPTY_SELECTION"
SENSITIVE_PATH = "SENSITIVE_PATH"
INVALID_ROOT = "INVALID_ROOT"
IO_ERROR = "IO_ERROR"
INPUT_CHANGED = "INPUT_CHANGED"
DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
OUTPUT_NOT_ALLOWED = "OUTPUT_NOT_ALLOWED"
OUTPUT_EXISTS = "OUTPUT_EXISTS"
VERIFY_FAILED = "VERIFY_FAILED"
INVALID_KEY = "INVALID_KEY"
TASK_NOT_FOUND = "TASK_NOT_FOUND"
IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
LOCAL_STORE_CONFLICT = "LOCAL_STORE_CONFLICT"
STATE_INVALID = "STATE_INVALID"
BUSY = "BUSY"
CONFIG_INVALID = "CONFIG_INVALID"
BUCKET_NOT_PRIVATE = "BUCKET_NOT_PRIVATE"
INVALID_OBJECT_KEY = "INVALID_OBJECT_KEY"
REMOTE_CONFLICT = "REMOTE_CONFLICT"
REMOTE_INTEGRITY = "REMOTE_INTEGRITY"
REMOTE_AUTH = "REMOTE_AUTH"
REMOTE_ERROR = "REMOTE_ERROR"
REMOTE_UNKNOWN = "REMOTE_UNKNOWN"
REMOTE_DELETE_UNCONFIRMED = "REMOTE_DELETE_UNCONFIRMED"
LINK_EXPIRED = "LINK_EXPIRED"


class DeliveryError(Exception):
    """Raised with a stable machine-readable code and a human message."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
